# Generated by Django 3.1 on 2021-08-05 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('work_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhour',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
