# Generated by Django 3.1 on 2021-11-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='work_type',
            field=models.IntegerField(choices=[(0, '휴일'), (1, '근무'), (2, '휴가'), (3, '반차')], default=0),
        ),
    ]
