# Generated by Django 3.1.7 on 2021-03-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20210323_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduleapproved',
            name='approved_type',
            field=models.IntegerField(choices=[(1, 'waiting'), (2, 'approved'), (3, 'reject')], default=1),
        ),
    ]
