# Generated by Django 3.1 on 2021-08-05 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0003_auto_20210325_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='work_type',
            field=models.IntegerField(choices=[(0, 'holiday'), (1, 'work'), (2, 'vacation'), (3, 'halfway')], default=0),
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(default='작성된 ToDo가 없습니다')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('title', models.CharField(max_length=50)),
                ('context', models.TextField(default='내용이 없습니다')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
