# Generated by Django 3.1 on 2022-04-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0003_auto_20220111_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='file',
        ),
    ]
