# Generated by Django 3.1 on 2022-03-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_auto_20220315_1736'),
        ('authy', '0002_profile_vacation'),
    ]

    operations = [
    ]
